import {state,persist,addGold,addDiamonds,addXp} from "./state.js";import {BOSSES,WORLDS} from "./data.js";import {toast,showScreen,renderTop} from "./ui.js";
const canvas=document.querySelector("#game-canvas"),ctx=canvas.getContext("2d");let keys=new Set(),raf=0,game=null,last=0;
function resize(){canvas.width=Math.max(960,innerWidth*devicePixelRatio);canvas.height=Math.max(540,innerHeight*devicePixelRatio);canvas.style.width="100%";canvas.style.height="100%";ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener("resize",resize);resize();
addEventListener("keydown",e=>{const k=e.key.toLowerCase();if(["w","a","s","d"," "].includes(k)){keys.add(k);e.preventDefault()}if(k==="escape")document.querySelector("#pause-menu").classList.add("open")});addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));
document.querySelectorAll("[data-key]").forEach(b=>{const k=b.dataset.key;b.addEventListener("pointerdown",e=>{e.preventDefault();keys.add(k)});["pointerup","pointercancel","pointerleave"].forEach(x=>b.addEventListener(x,()=>keys.delete(k)))});
document.querySelectorAll("[data-action]").forEach(b=>b.addEventListener("pointerdown",()=>action(b.dataset.action)));
window.addEventListener("start-combat",e=>start(e.detail));
function start(d){cancelAnimationFrame(raf);const W=innerWidth,H=innerHeight;const boss=d.boss;game={world:d.world,mission:d.mission,boss,x:W*.25,y:H*.67,vx:0,vy:0,hp:100,maxHp:100,energy:100,combo:0,score:0,shake:0,enemies:[],projectiles:[],particles:[],time:0,won:false,dead:false};const count=boss?1:Math.min(7,2+Math.floor(d.mission/10));for(let i=0;i<count;i++)game.enemies.push(enemy(i,boss));document.querySelector("#mission-title").textContent=`WORLD ${d.world+1} • ${boss?"BOSS":"MISSION "+(d.mission+1)}`;document.querySelector("#mission-objective").textContent=boss?BOSSES[d.world]:"Defeat all enemies";document.querySelector("#combat-message").textContent=`${WORLDS[d.world][0]} • ${boss?BOSSES[d.world]:"MISSION "+(d.mission+1)}`;renderTop();last=performance.now();raf=requestAnimationFrame(loop)}
function enemy(i,boss){return {x:innerWidth*(.62+i*.07),y:innerHeight*(.57+(i%3)*.08),r:boss?52:26,hp:boss?260:45,maxHp:boss?260:45,vx:0,vy:0,hit:0,boss}}
function action(a){if(!game||game.dead||game.won)return;if(a==="strike"||a==="skill"){const range=a==="skill"?220:145;let hit=0;for(const e of game.enemies){if(Math.abs(e.x-game.x)<range&&Math.abs(e.y-game.y)<100){e.hp-=a==="skill"?55:25;e.hit=8;hit++;game.combo++;state.save.stats.kills+=e.hp<=0?1:0;burst(e.x,e.y,a==="skill"?"#a34dff":"#f4a52f",a==="skill"?14:7)}}if(hit){game.score+=hit*25;game.shake=8}else if(a==="dash"){game.x+=keys.has("d")?150:keys.has("a")?-150:150;game.x=Math.max(80,Math.min(innerWidth-80,game.x));burst(game.x,game.y,"#7f44ff",12)}else if(a==="jump"){game.y-=90;setTimeout(()=>game&&(game.y+=90),250)}else if(a==="shield"){game.energy=Math.min(100,game.energy+20)}else if(a==="potion"){if(state.save.potions>0&&game.hp<game.maxHp){state.save.potions--;state.save.stats.deaths=Math.max(0,state.save.stats.deaths);game.hp=Math.min(game.maxHp,game.hp+45);persist();renderTop()}}}
function loop(t){const dt=Math.min(.032,(t-last)/1000);last=t;update(dt);draw();if(game&&!game.won&&!game.dead)raf=requestAnimationFrame(loop)}
function update(dt){if(!game)return;game.time+=dt;let sp=250;game.vx=(keys.has("d")?sp:0)+(keys.has("a")?-sp:0);game.vy=(keys.has("s")?sp:0)+(keys.has("w")?-sp:0);game.x+=game.vx*dt;game.y+=game.vy*dt;game.x=Math.max(70,Math.min(innerWidth-70,game.x));game.y=Math.max(180,Math.min(innerHeight-130,game.y));for(const e of game.enemies){const dx=game.x-e.x,dy=game.y-e.y,dist=Math.hypot(dx,dy)||1;e.vx=dx/dist*55;e.vy=dy/dist*55;e.x+=e.vx*dt;e.y+=e.vy*dt;e.hit=Math.max(0,e.hit-dt*30);if(dist<70&&!e.hit){game.hp-=e.boss?18*dt:10*dt;game.shake=4}}for(let i=game.enemies.length-1;i>=0;i--)if(game.enemies[i].hp<=0){burst(game.enemies[i].x,game.enemies[i].y,"#c43cff",20);game.enemies.splice(i,1)}for(const p of game.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}game.particles=game.particles.filter(p=>p.life>0);if(game.hp<=0){game.dead=true;state.save.stats.deaths++;persist();document.querySelector("#combat-message").textContent="DEFEATED • TRY AGAIN";setTimeout(()=>showScreen("home"),1800)}if(game.enemies.length===0&&!game.won)winMission()}
function winMission(){game.won=true;const s=state.save;if(game.boss){s.bossWins++;s.completed=Math.max(s.completed,(s.world+1)*100);if(s.world<19){s.world++;s.mission=0}}else{const m=game.mission;if(m===s.mission){s.mission=Math.min(99,s.mission+1);s.completed=Math.max(s.completed,s.world*100+s.mission);if(s.mission===100&&s.world<19){s.world++;s.mission=0}}}s.gold+=120+game.score;s.diamonds+=game.boss?80:10;addXp(game.boss?500:120);persist();renderTop();document.querySelector("#combat-message").textContent=`MISSION CLEAR • +${game.boss?80:10} 💎 • +${120+game.score} 🪙`;setTimeout(()=>showScreen("home"),2200)}
function burst(x,y,color,n){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,sp=40+Math.random()*180;game.particles.push({x,y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,life:.5+Math.random()*.6,color})}}
function draw(){const W=innerWidth,H=innerHeight;ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#080619");g.addColorStop(.55,"#10102c");g.addColorStop(1,"#03030a");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle="#15152c";ctx.fillRect(0,H*.68,W,H*.32);for(let i=0;i<13;i++){ctx.fillStyle=`rgba(130,62,255,${.06+(i%3)*.03})`;ctx.fillRect(i*W/13,H*.2+(i%4)*18,W/18,H*.48)}ctx.fillStyle="#d5c3ff";ctx.beginPath();ctx.arc(W*.75,H*.2,70,0,Math.PI*2);ctx.fill();ctx.fillStyle="#24114c";ctx.beginPath();ctx.arc(W*.78,H*.2,70,0,Math.PI*2);ctx.fill();for(let i=0;i<8;i++){ctx.strokeStyle="rgba(180,60,255,.25)";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(W*.5+i*90,H*.68);ctx.lineTo(W*.5+i*90-80,H*.35);ctx.stroke()}drawHero();for(const e of game.enemies)drawEnemy(e);for(const p of game.particles){ctx.globalAlpha=Math.max(0,p.life*1.6);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,3+p.life*4,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}drawBossHp()}
function drawHero(){const x=game.x,y=game.y;ctx.save();ctx.translate(x,y);ctx.shadowBlur=22;ctx.shadowColor="#a947ff";ctx.fillStyle="#131321";ctx.beginPath();ctx.ellipse(0,30,31,45,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#e5c6b0";ctx.beginPath();ctx.arc(0,-22,18,0,Math.PI*2);ctx.fill();ctx.fillStyle="#111";ctx.beginPath();ctx.arc(-3,-28,20,Math.PI,Math.PI*2);ctx.fill();ctx.strokeStyle="#b33cff";ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(18,5);ctx.lineTo(68,-40);ctx.stroke();ctx.strokeStyle="#f2d6ff";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(18,5);ctx.lineTo(68,-40);ctx.stroke();ctx.restore()}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);ctx.shadowBlur=16;ctx.shadowColor=e.boss?"#ff3b32":"#7f3cff";ctx.fillStyle=e.boss?"#35100f":"#151122";ctx.beginPath();ctx.arc(0,0,e.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle=e.boss?"#ff4c32":"#9c4dff";ctx.lineWidth=3;ctx.stroke();ctx.fillStyle="#ff475e";ctx.fillRect(-12,-5,8,5);ctx.fillRect(4,-5,8,5);ctx.restore();ctx.fillStyle="#31101a";ctx.fillRect(e.x-e.r,e.y-e.r-16,e.r*2,5);ctx.fillStyle=e.boss?"#ff4a32":"#a749ff";ctx.fillRect(e.x-e.r,e.y-e.r-16,e.r*2*(e.hp/e.maxHp),5)}
function drawBossHp(){if(!game.boss)return;ctx.fillStyle="#130c18";ctx.fillRect(innerWidth*.25,95,innerWidth*.5,15);ctx.fillStyle="#df3f48";ctx.fillRect(innerWidth*.25,95,innerWidth*.5*(game.enemies[0]?.hp||0)/(game.enemies[0]?.maxHp||1),15);ctx.fillStyle="#fff";ctx.font="bold 13px system-ui";ctx.textAlign="center";ctx.fillText(BOSSES[game.world],innerWidth*.5,88)}
