import {state,persist} from "./state.js";import {WORLDS,WEAPONS,ARMOR,EMOTES,SKILLS,AVATARS,BOSSES} from "./data.js";import {addItem,hasItem,spendGold,spendDiamonds,addGold,addDiamonds,avatarName} from "./storage.js";
const $=q=>document.querySelector(q);
export function showScreen(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");state.screen=id;renderTop()}
export function toast(msg){const d=document.createElement("div");d.className="toast";d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),1900)}
export function renderTop(){const s=state.save;$("#gold").textContent=s.gold.toLocaleString();$("#diamonds").textContent=s.diamonds.toLocaleString();$("#energy").textContent=s.energy;$("#max-energy").textContent=s.maxEnergy;$("#selected-world").textContent=`WORLD ${s.world+1} • ${WORLDS[s.world][0].toUpperCase()}`;$("#start-label").textContent=`MISSION ${s.mission+1} • ⚡10`;$("#combat-name").textContent=s.name;$("#combat-gold").textContent=s.gold.toLocaleString();$("#combat-diamond").textContent=s.diamonds.toLocaleString();$("#q1").textContent=`${Math.min(3,s.completed%4)}/3`;$("#q2").textContent=`${Math.min(1,s.bossWins)}/1`;$("#q3").textContent=`${Math.min(5,s.potions)}/5`}
export function openPanel(type){state.panel=type;showScreen("panel");const titles={shop:["STORE","Weapons, armor and rare gear"],inventory:["INVENTORY","Equip your strongest gear"],weapons:["WEAPONS","Choose your active weapon"],emotes:["EMOTES","Equip emotes for the character wheel"],skills:["SKILLS","Upgrade your combat abilities"],missions:["MISSIONS","100 missions in every world"],profile:["PROFILE","Level, avatar and achievements"],ranking:["RANKING","Local and online-ready rankings"],friends:["FRIENDS","Invite friends for co-op later"],guild:["GUILD","Build your squad"],settings:["SETTINGS","Game, audio and account settings"],events:["EVENTS","Seasonal challenges and rewards"],daily:["DAILY GIFT","One free reward every day"],wheel:["LUCK WHEEL","Spin for free or premium rewards"],boss:["BOSS FIGHT","Challenge the next guardian"],messages:["MESSAGES","System and squad messages"]};$("#panel-title").textContent=titles[type]?.[0]||type.toUpperCase();$("#panel-subtitle").textContent=titles[type]?.[1]||"";renderPanel(type)}
function button(text,cls=""){return `<button class="wide-btn ${cls}">${text}</button>`}
export function renderPanel(type){const s=state.save;let h="";
if(type==="shop"||type==="weapons"){const arr=type==="shop"?[...WEAPONS,...ARMOR]:WEAPONS;h=`<div class="shop-grid">${arr.map(i=>`<article class="item"><div class="icon">${i[1]}</div><h3>${i[0]}</h3><p>${i[4]} POWER • ${i[3]}</p>${hasItem(s,i[0])?button("OWNED","owned"):button(`BUY ${i[2]} ${i[3]==="gold"?"🪙":"💎"}`)}</article>`).join("")}</div>`}
else if(type==="inventory"){h=`<div class="inventory-grid">${s.owned.map(n=>{const i=[...WEAPONS,...ARMOR].find(x=>x[0]===n);return `<article class="item"><div class="icon">${i?.[1]||"🎒"}</div><h3>${n}</h3><p>Owned gear</p>${button(s.selectedWeapon===n||s.selectedArmor===n?"EQUIPPED":"EQUIP")}</article>`}).join("")}</div>`}
else if(type==="emotes"){h=`<div class="emote-grid">${EMOTES.map(i=>`<article class="item"><div class="icon">${i[1]}</div><h3>${i[0]}</h3><p>Premium emote</p>${button(s.ownedEmotes.includes(i[0])?"OWNED":`BUY ${i[2]} 💎`)}</article>`).join("")}</div>`}
else if(type==="skills"){h=`<div class="shop-grid">${SKILLS.map(i=>`<article class="item"><div class="icon">${i[1]}</div><h3>${i[0]}</h3><p>${i[2]}</p>${button(s.skills.includes(i[0])?"UNLOCKED":`UPGRADE ${i[3]} 🪙`)}</article>`).join("")}</div>`}
else if(type==="missions"){h=`<div class="mission-grid">${Array.from({length:100},(_,i)=>{const done=i<s.mission,cur=i===s.mission;return `<button class="mission ${done?"done":cur?"current":"locked"}" data-mission="${i}"><b>${i+1}</b><div>${done?"✓ CLEAR":cur?"▶ PLAY":"🔒 LOCK"}</div><small>★ ${done?3:0}</small></button>`}).join("")}</div>`}
else if(type==="profile"){h=`<div class="profile-card"><div style="font-size:80px">${avatarName(s)}</div><h2>${s.name}</h2><p>LEVEL ${s.level} • ${s.xp}/${s.nextXp} XP</p><div class="avatar-grid">${AVATARS.map((a,i)=>`<button class="avatar ${i===s.selectedAvatar?"selected":""}" data-avatar="${i}">${a}</button>`).join("")}</div><h3>ACHIEVEMENTS</h3><div class="shop-grid">${["First Blood","Hunter","Boss Slayer","World Walker","Collector","Legend"].map((x,i)=>`<article class="item"><h3>${x}</h3><p>${s.completed>=(i+1)*10?"UNLOCKED":"🔒 Keep playing"}</p></article>`).join("")}</div></div>`}
else if(type==="daily"){h=`<div class="wheel-wrap"><div class="item"><div class="icon">🎁</div><h2>DAILY REWARD</h2><p>Claim once per day. The reward is saved offline.</p>${button("CLAIM DAILY GIFT","daily-claim")}</div></div>`}
else if(type==="wheel"){h=`<div class="wheel-wrap"><div id="wheel" class="wheel"><span>🎁</span></div>${button("SPIN FREE WHEEL","spin")}${button("PREMIUM SPIN • 25 💎","premium-spin")}</div>`}
else if(type==="boss"){const b=BOSSES[s.world];h=`<div class="profile-card"><div class="icon" style="font-size:100px">👹</div><h2>${b}</h2><p>WORLD ${s.world+1} • BOSS MISSION 100</p><p>Defeat the guardian to unlock the next world.</p>${button("ENTER BOSS FIGHT","boss-start")}</div>`}
else if(type==="ranking"){h=`<div class="shop-grid">${["ArcaneX","VoidHunter","NightMage","StormLord","ShadowReaper","CrystalFox","IronSoul","DragonBorn"].map((n,i)=>`<article class="item"><h3>#${i+1} ${n}</h3><p>${Math.max(1,1000-i*83)} rating • ${20-i} worlds</p></article>`).join("")}</div>`}
else if(type==="friends"){h=`<div class="profile-card"><h2>FRIENDS / CO-OP</h2><p>Local co-op-ready interface. Online matchmaking can be connected to a server later without changing the game UI.</p>${button("CREATE PARTY")}${button("JOIN PARTY")}</div>`}
else if(type==="settings"){h=`<div class="profile-card"><h2>SETTINGS</h2><p>Landscape mode • Neon UI • Music enabled • Effects enabled • Offline save enabled</p>${button("RESET LOCAL SAVE","reset-save")}${button("CLOSE SETTINGS")}</div>`}
else if(type==="events"){h=`<div class="shop-grid">${["Shadow Awakening","Boss Rush","Weapon Hunt","Seven Day Trial"].map((x,i)=>`<article class="item"><div class="icon">${["🌑","👹","⚔️","🎯"][i]}</div><h3>${x}</h3><p>Event progress ${Math.min(100,s.completed*2+i*7)}/100</p></article>`).join("")}</div>`}
else if(type==="messages"){h=`<div class="profile-card"><h2>INBOX</h2><p>Welcome to Wizard Dash.</p><p>Daily gift and mission rewards are waiting.</p></div>`}
else if(type==="guild"){h=`<div class="profile-card"><h2>GUILD</h2><p>Build a squad, share rewards and prepare for co-op battles.</p>${button("CREATE GUILD")}${button("JOIN GUILD")}</div>`}
$("#panel-content").innerHTML=h;attachPanelHandlers(type)}
function attachPanelHandlers(type){const s=state.save;document.querySelectorAll("[data-avatar]").forEach(b=>b.onclick=()=>{s.selectedAvatar=+b.dataset.avatar;persist();renderPanel("profile")});document.querySelectorAll("[data-mission]").forEach(b=>b.onclick=()=>{const m=+b.dataset.mission;if(m<=s.mission){s.mission=m;persist();startMission(m)}else toast("Complete missions in order to unlock this one.")});document.querySelectorAll(".item button").forEach(b=>b.onclick=()=>{const txt=b.textContent;const item=b.closest(".item")?.querySelector("h3")?.textContent;if(!item)return;const all=[...WEAPONS,...ARMOR];const data=all.find(x=>x[0]===item);if(txt.includes("BUY")){if(data[3]==="gold"?spendGold(data[2]):spendDiamonds(data[2])){addItem(s,item);toast(`${item} purchased`);renderPanel(type);renderTop()}else toast("Not enough currency")}else if(txt==="EQUIP"){if(WEAPONS.some(x=>x[0]===item))s.selectedWeapon=item;else s.selectedArmor=item;persist();toast(`${item} equipped`);renderPanel(type)}});
document.querySelectorAll(".emote-grid button").forEach(b=>b.onclick=()=>{const item=b.closest(".item")?.querySelector("h3")?.textContent;const d=EMOTES.find(x=>x[0]===item);if(s.ownedEmotes.includes(item))return toast("Already owned");if(spendDiamonds(d[2])){s.ownedEmotes.push(item);persist();renderPanel("emotes");renderTop();toast("Emote unlocked") }else toast("Not enough diamonds")});
document.querySelectorAll(".shop-grid .item button").forEach(()=>{});
document.querySelector(".daily-claim")?.addEventListener("click",()=>claimDaily());
document.querySelector(".spin")?.addEventListener("click",()=>spinWheel(false));document.querySelector(".premium-spin")?.addEventListener("click",()=>spinWheel(true));document.querySelector(".boss-start")?.addEventListener("click",()=>startBoss());document.querySelector(".reset-save")?.addEventListener("click",()=>{localStorage.removeItem("wizardDashSaveV3");location.reload()})}
function claimDaily(){const s=state.save,t=new Date().toDateString();if(s.dailyClaim===t)return toast("Daily reward already claimed");s.dailyClaim=t;s.diamonds+=50;s.gold+=500;persist();renderTop();renderPanel("daily");toast("+500 gold +50 diamonds")}
function spinWheel(premium){const s=state.save;if(premium&&!spendDiamonds(25))return toast("Not enough diamonds");if(!premium&&s.wheelClaim===new Date().toDateString())return toast("Daily free spin already used");const wheel=$("#wheel");wheel.style.transform=`rotate(${720+Math.floor(Math.random()*360)}deg)`;setTimeout(()=>{const rewards=[["500 gold",()=>s.gold+=500],["50 diamonds",()=>s.diamonds+=50],["Potion",()=>s.potions++],["1000 gold",()=>s.gold+=1000],["20 diamonds",()=>s.diamonds+=20]];const r=rewards[Math.floor(Math.random()*rewards.length)];r[1]();if(!premium)s.wheelClaim=new Date().toDateString();persist();renderTop();toast(`Wheel reward: ${r[0]}`)},1100)}
export function startMission(m=state.save.mission){if(m>state.save.mission)return toast("Locked mission");showScreen("combat");window.dispatchEvent(new CustomEvent("start-combat",{detail:{world:state.save.world,mission:m,boss:false}}))}
export function startBoss(){showScreen("combat");window.dispatchEvent(new CustomEvent("start-combat",{detail:{world:state.save.world,mission:99,boss:true}}))}
export function attachGlobal(){document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openPanel(b.dataset.open));document.querySelectorAll("[data-back-home]").forEach(b=>b.onclick=()=>showScreen("home"));$("#panel-back").onclick=()=>showScreen("home");$("#panel-close").onclick=()=>showScreen("home");$("#profile-mini").onclick=()=>openPanel("profile");$("#map-selector").onclick=()=>showScreen("map");$("#start-btn").onclick=()=>startMission();$("#hero-emote").onclick=()=>openPanel("emotes");$("#combat-pause").onclick=()=>document.querySelector("#pause-menu").classList.add("open");$("#resume").onclick=()=>document.querySelector("#pause-menu").classList.remove("open");$("#quit-combat").onclick=()=>showScreen("home");renderTop()}
export function renderMap(){const s=state.save;$("#world-grid").innerHTML=WORLDS.map((w,i)=>{const unlocked=i===0||s.completed>=i*100;const progress=i<s.world?100:i===s.world?s.mission:0;return `<button class="world ${unlocked?"":"locked"} ${i===s.world?"active":""}" data-world="${i}"><h3>${w[1]} ${i+1}. ${w[0]}</h3><p>${unlocked?`${progress}/100 missions complete`:"🔒 Complete previous world"}</p><div class="progress"><i style="width:${progress}%"></i></div></button>`}).join("");document.querySelectorAll("[data-world]").forEach(b=>b.onclick=()=>{const i=+b.dataset.world;if(i===0||s.completed>=i*100){s.world=i;s.mission=Math.min(s.mission,99);persist();renderTop();showScreen("home")}else toast("World locked.")})}
